# Configuration Options
title: Engineering Portfolio
# author: "Cecilia Li"
# address: Brea, California
theme: minima

header-pages:
  - individualprojects.html
  - clinicprojects.html
  - labprojects.html
  - resume.html